spring:
  datasource:
    url: jdbc:mysql://cnu-yb.mysql.polardb.rds.aliyuncs.com:3306/pms_database?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: yb
    password: 520520lw!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com:
      example:
        pmscode: debug

