spring:
  datasource:
    url: jdbc:mysql://cnu-yb.mysql.polardb.rds.aliyuncs.com:3306/pms_database?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: yb
    password: 520520lw!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com:
      example:
        pmscode: debug
    org:
      mybatis: TRACE

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true

